name: Build and publish addon binaries
run-name: Build and publish addon binaries for macOS ARM64

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and publish addon binaries
    runs-on: macos-15
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./package.json
          registry-url: https://npm.pkg.github.com
          scope: "@hereiskevin"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: ./package.json

      - name: Build addon for master branch
        run: |
          pnpm install --frozen-lockfile
          pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
